/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Adjustment = IDL.Record({
  'date' : Timestamp,
  'notes' : IDL.Text,
  'amount' : IDL.Nat64,
  'repId' : IDL.Nat,
});
export const Consignment = IDL.Record({
  'date' : Timestamp,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'repId' : IDL.Nat,
});
export const Payout = IDL.Record({
  'date' : Timestamp,
  'notes' : IDL.Text,
  'amount' : IDL.Nat64,
  'repId' : IDL.Nat,
});
export const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat64 });
export const Rep = IDL.Record({ 'name' : IDL.Text });
export const ReturnModel = IDL.Record({
  'date' : Timestamp,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'repId' : IDL.Nat,
});
export const Sale = IDL.Record({
  'date' : Timestamp,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat64,
  'repId' : IDL.Nat,
});
export const SettlementStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const RepBalance = IDL.Record({
  'consignmentValue' : IDL.Nat64,
  'salesValue' : IDL.Nat64,
  'finalBalance' : IDL.Nat64,
  'returnsValue' : IDL.Nat64,
  'adjustmentValue' : IDL.Nat64,
  'payoutValue' : IDL.Nat64,
});
export const SettlementPeriodView = IDL.Record({
  'id' : IDL.Nat,
  'status' : SettlementStatus,
  'endDate' : Timestamp,
  'statementIds' : IDL.Vec(IDL.Nat),
  'closingBalances' : IDL.Vec(IDL.Tuple(IDL.Nat, RepBalance)),
  'openingBalances' : IDL.Vec(IDL.Tuple(IDL.Nat, RepBalance)),
  'startDate' : Timestamp,
});

export const idlService = IDL.Service({
  'addAdjustment' : IDL.Func(
      [IDL.Nat, IDL.Nat64, Timestamp, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addConsignment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, Timestamp],
      [IDL.Nat],
      [],
    ),
  'addPayout' : IDL.Func(
      [IDL.Nat, IDL.Nat64, Timestamp, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func([IDL.Text, IDL.Nat64], [IDL.Nat], []),
  'addRep' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addReturn' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, Timestamp], [IDL.Nat], []),
  'addSale' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, Timestamp],
      [IDL.Nat],
      [],
    ),
  'closeSettlementPeriod' : IDL.Func([IDL.Nat], [], []),
  'createSettlementPeriod' : IDL.Func([Timestamp, Timestamp], [IDL.Nat], []),
  'getAdjustment' : IDL.Func([IDL.Nat], [Adjustment], ['query']),
  'getAdjustmentsByRep' : IDL.Func([IDL.Nat], [IDL.Vec(Adjustment)], ['query']),
  'getAllAdjustments' : IDL.Func([], [IDL.Vec(Adjustment)], ['query']),
  'getAllConsignments' : IDL.Func([], [IDL.Vec(Consignment)], ['query']),
  'getAllPayouts' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReps' : IDL.Func([], [IDL.Vec(Rep)], ['query']),
  'getAllReturns' : IDL.Func([], [IDL.Vec(ReturnModel)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getAllSettlementPeriods' : IDL.Func(
      [],
      [IDL.Vec(SettlementPeriodView)],
      ['query'],
    ),
  'getConsignment' : IDL.Func([IDL.Nat], [Consignment], ['query']),
  'getConsignmentsByRep' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Consignment)],
      ['query'],
    ),
  'getPayout' : IDL.Func([IDL.Nat], [Payout], ['query']),
  'getPayoutsByRep' : IDL.Func([IDL.Nat], [IDL.Vec(Payout)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getRep' : IDL.Func([IDL.Nat], [Rep], ['query']),
  'getReturn' : IDL.Func([IDL.Nat], [ReturnModel], ['query']),
  'getReturnsByRep' : IDL.Func([IDL.Nat], [IDL.Vec(ReturnModel)], ['query']),
  'getSale' : IDL.Func([IDL.Nat], [Sale], ['query']),
  'getSalesByRep' : IDL.Func([IDL.Nat], [IDL.Vec(Sale)], ['query']),
  'getSettlementPeriod' : IDL.Func(
      [IDL.Nat],
      [SettlementPeriodView],
      ['query'],
    ),
  'getSettlementPeriodsByStatus' : IDL.Func(
      [SettlementStatus],
      [IDL.Vec(SettlementPeriodView)],
      ['query'],
    ),
  'getSettlementPeriodsForRep' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SettlementPeriodView)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Adjustment = IDL.Record({
    'date' : Timestamp,
    'notes' : IDL.Text,
    'amount' : IDL.Nat64,
    'repId' : IDL.Nat,
  });
  const Consignment = IDL.Record({
    'date' : Timestamp,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'repId' : IDL.Nat,
  });
  const Payout = IDL.Record({
    'date' : Timestamp,
    'notes' : IDL.Text,
    'amount' : IDL.Nat64,
    'repId' : IDL.Nat,
  });
  const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat64 });
  const Rep = IDL.Record({ 'name' : IDL.Text });
  const ReturnModel = IDL.Record({
    'date' : Timestamp,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'repId' : IDL.Nat,
  });
  const Sale = IDL.Record({
    'date' : Timestamp,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat64,
    'repId' : IDL.Nat,
  });
  const SettlementStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
  });
  const RepBalance = IDL.Record({
    'consignmentValue' : IDL.Nat64,
    'salesValue' : IDL.Nat64,
    'finalBalance' : IDL.Nat64,
    'returnsValue' : IDL.Nat64,
    'adjustmentValue' : IDL.Nat64,
    'payoutValue' : IDL.Nat64,
  });
  const SettlementPeriodView = IDL.Record({
    'id' : IDL.Nat,
    'status' : SettlementStatus,
    'endDate' : Timestamp,
    'statementIds' : IDL.Vec(IDL.Nat),
    'closingBalances' : IDL.Vec(IDL.Tuple(IDL.Nat, RepBalance)),
    'openingBalances' : IDL.Vec(IDL.Tuple(IDL.Nat, RepBalance)),
    'startDate' : Timestamp,
  });
  
  return IDL.Service({
    'addAdjustment' : IDL.Func(
        [IDL.Nat, IDL.Nat64, Timestamp, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addConsignment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, Timestamp],
        [IDL.Nat],
        [],
      ),
    'addPayout' : IDL.Func(
        [IDL.Nat, IDL.Nat64, Timestamp, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func([IDL.Text, IDL.Nat64], [IDL.Nat], []),
    'addRep' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addReturn' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, Timestamp],
        [IDL.Nat],
        [],
      ),
    'addSale' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, Timestamp],
        [IDL.Nat],
        [],
      ),
    'closeSettlementPeriod' : IDL.Func([IDL.Nat], [], []),
    'createSettlementPeriod' : IDL.Func([Timestamp, Timestamp], [IDL.Nat], []),
    'getAdjustment' : IDL.Func([IDL.Nat], [Adjustment], ['query']),
    'getAdjustmentsByRep' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Adjustment)],
        ['query'],
      ),
    'getAllAdjustments' : IDL.Func([], [IDL.Vec(Adjustment)], ['query']),
    'getAllConsignments' : IDL.Func([], [IDL.Vec(Consignment)], ['query']),
    'getAllPayouts' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReps' : IDL.Func([], [IDL.Vec(Rep)], ['query']),
    'getAllReturns' : IDL.Func([], [IDL.Vec(ReturnModel)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getAllSettlementPeriods' : IDL.Func(
        [],
        [IDL.Vec(SettlementPeriodView)],
        ['query'],
      ),
    'getConsignment' : IDL.Func([IDL.Nat], [Consignment], ['query']),
    'getConsignmentsByRep' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Consignment)],
        ['query'],
      ),
    'getPayout' : IDL.Func([IDL.Nat], [Payout], ['query']),
    'getPayoutsByRep' : IDL.Func([IDL.Nat], [IDL.Vec(Payout)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getRep' : IDL.Func([IDL.Nat], [Rep], ['query']),
    'getReturn' : IDL.Func([IDL.Nat], [ReturnModel], ['query']),
    'getReturnsByRep' : IDL.Func([IDL.Nat], [IDL.Vec(ReturnModel)], ['query']),
    'getSale' : IDL.Func([IDL.Nat], [Sale], ['query']),
    'getSalesByRep' : IDL.Func([IDL.Nat], [IDL.Vec(Sale)], ['query']),
    'getSettlementPeriod' : IDL.Func(
        [IDL.Nat],
        [SettlementPeriodView],
        ['query'],
      ),
    'getSettlementPeriodsByStatus' : IDL.Func(
        [SettlementStatus],
        [IDL.Vec(SettlementPeriodView)],
        ['query'],
      ),
    'getSettlementPeriodsForRep' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SettlementPeriodView)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };