/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Payout {
    date: Timestamp;
    notes: string;
    amount: bigint;
    repId: bigint;
}
export interface Consignment {
    date: Timestamp;
    productId: bigint;
    quantity: bigint;
    repId: bigint;
}
export interface RepBalance {
    consignmentValue: bigint;
    salesValue: bigint;
    finalBalance: bigint;
    returnsValue: bigint;
    adjustmentValue: bigint;
    payoutValue: bigint;
}
export interface Rep {
    name: string;
}
export interface SettlementPeriodView {
    id: bigint;
    status: SettlementStatus;
    endDate: Timestamp;
    statementIds: Array<bigint>;
    closingBalances: Array<[bigint, RepBalance]>;
    openingBalances: Array<[bigint, RepBalance]>;
    startDate: Timestamp;
}
export interface Adjustment {
    date: Timestamp;
    notes: string;
    amount: bigint;
    repId: bigint;
}
export interface Sale {
    date: Timestamp;
    productId: bigint;
    quantity: bigint;
    unitPrice: bigint;
    repId: bigint;
}
export interface ReturnModel {
    date: Timestamp;
    productId: bigint;
    quantity: bigint;
    repId: bigint;
}
export interface Product {
    name: string;
    price: bigint;
}
export enum SettlementStatus {
    closed = "closed",
    open = "open"
}
export interface backendInterface {
    addAdjustment(repId: bigint, amount: bigint, date: Timestamp, notes: string): Promise<bigint>;
    addConsignment(repId: bigint, productId: bigint, quantity: bigint, date: Timestamp): Promise<bigint>;
    addPayout(repId: bigint, amount: bigint, date: Timestamp, notes: string): Promise<bigint>;
    addProduct(name: string, price: bigint): Promise<bigint>;
    addRep(name: string): Promise<bigint>;
    addReturn(repId: bigint, productId: bigint, quantity: bigint, date: Timestamp): Promise<bigint>;
    addSale(repId: bigint, productId: bigint, quantity: bigint, unitPrice: bigint, date: Timestamp): Promise<bigint>;
    closeSettlementPeriod(settlementId: bigint): Promise<void>;
    createSettlementPeriod(startDate: Timestamp, endDate: Timestamp): Promise<bigint>;
    getAdjustment(id: bigint): Promise<Adjustment>;
    getAdjustmentsByRep(repId: bigint): Promise<Array<Adjustment>>;
    getAllAdjustments(): Promise<Array<Adjustment>>;
    getAllConsignments(): Promise<Array<Consignment>>;
    getAllPayouts(): Promise<Array<Payout>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllReps(): Promise<Array<Rep>>;
    getAllReturns(): Promise<Array<ReturnModel>>;
    getAllSales(): Promise<Array<Sale>>;
    getAllSettlementPeriods(): Promise<Array<SettlementPeriodView>>;
    getConsignment(id: bigint): Promise<Consignment>;
    getConsignmentsByRep(repId: bigint): Promise<Array<Consignment>>;
    getCurrentTimestamp(): Promise<Timestamp>;
    getPayout(id: bigint): Promise<Payout>;
    getPayoutsByRep(repId: bigint): Promise<Array<Payout>>;
    getProduct(id: bigint): Promise<Product>;
    getRep(id: bigint): Promise<Rep>;
    getReturn(id: bigint): Promise<ReturnModel>;
    getReturnsByRep(repId: bigint): Promise<Array<ReturnModel>>;
    getSale(id: bigint): Promise<Sale>;
    getSalesByRep(repId: bigint): Promise<Array<Sale>>;
    getSettlementPeriod(id: bigint): Promise<SettlementPeriodView>;
    getSettlementPeriodsByStatus(status: SettlementStatus): Promise<Array<SettlementPeriodView>>;
    getSettlementPeriodsForRep(repId: bigint): Promise<Array<SettlementPeriodView>>;
}
import type { RepBalance as _RepBalance, SettlementPeriodView as _SettlementPeriodView, SettlementStatus as _SettlementStatus, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdjustment(arg0: bigint, arg1: bigint, arg2: Timestamp, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdjustment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdjustment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addConsignment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addConsignment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addConsignment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPayout(arg0: bigint, arg1: bigint, arg2: Timestamp, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayout(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayout(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1);
            return result;
        }
    }
    async addRep(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRep(arg0);
            return result;
        }
    }
    async addReturn(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReturn(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReturn(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSale(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async closeSettlementPeriod(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeSettlementPeriod(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeSettlementPeriod(arg0);
            return result;
        }
    }
    async createSettlementPeriod(arg0: Timestamp, arg1: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSettlementPeriod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSettlementPeriod(arg0, arg1);
            return result;
        }
    }
    async getAdjustment(arg0: bigint): Promise<Adjustment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdjustment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdjustment(arg0);
            return result;
        }
    }
    async getAdjustmentsByRep(arg0: bigint): Promise<Array<Adjustment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdjustmentsByRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdjustmentsByRep(arg0);
            return result;
        }
    }
    async getAllAdjustments(): Promise<Array<Adjustment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdjustments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdjustments();
            return result;
        }
    }
    async getAllConsignments(): Promise<Array<Consignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConsignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConsignments();
            return result;
        }
    }
    async getAllPayouts(): Promise<Array<Payout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayouts();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllReps(): Promise<Array<Rep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReps();
            return result;
        }
    }
    async getAllReturns(): Promise<Array<ReturnModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReturns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReturns();
            return result;
        }
    }
    async getAllSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return result;
        }
    }
    async getAllSettlementPeriods(): Promise<Array<SettlementPeriodView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSettlementPeriods();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSettlementPeriods();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConsignment(arg0: bigint): Promise<Consignment> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsignment(arg0);
            return result;
        }
    }
    async getConsignmentsByRep(arg0: bigint): Promise<Array<Consignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsignmentsByRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsignmentsByRep(arg0);
            return result;
        }
    }
    async getCurrentTimestamp(): Promise<Timestamp> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTimestamp();
            return result;
        }
    }
    async getPayout(arg0: bigint): Promise<Payout> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayout(arg0);
            return result;
        }
    }
    async getPayoutsByRep(arg0: bigint): Promise<Array<Payout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutsByRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutsByRep(arg0);
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async getRep(arg0: bigint): Promise<Rep> {
        if (this.processError) {
            try {
                const result = await this.actor.getRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRep(arg0);
            return result;
        }
    }
    async getReturn(arg0: bigint): Promise<ReturnModel> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturn(arg0);
            return result;
        }
    }
    async getReturnsByRep(arg0: bigint): Promise<Array<ReturnModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturnsByRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturnsByRep(arg0);
            return result;
        }
    }
    async getSale(arg0: bigint): Promise<Sale> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return result;
        }
    }
    async getSalesByRep(arg0: bigint): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByRep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByRep(arg0);
            return result;
        }
    }
    async getSettlementPeriod(arg0: bigint): Promise<SettlementPeriodView> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettlementPeriod(arg0);
                return from_candid_SettlementPeriodView_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettlementPeriod(arg0);
            return from_candid_SettlementPeriodView_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettlementPeriodsByStatus(arg0: SettlementStatus): Promise<Array<SettlementPeriodView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettlementPeriodsByStatus(to_candid_SettlementStatus_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettlementPeriodsByStatus(to_candid_SettlementStatus_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettlementPeriodsForRep(arg0: bigint): Promise<Array<SettlementPeriodView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettlementPeriodsForRep(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettlementPeriodsForRep(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_SettlementPeriodView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SettlementPeriodView): SettlementPeriodView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SettlementStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SettlementStatus): SettlementStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SettlementStatus;
    endDate: _Timestamp;
    statementIds: Array<bigint>;
    closingBalances: Array<[bigint, _RepBalance]>;
    openingBalances: Array<[bigint, _RepBalance]>;
    startDate: _Timestamp;
}): {
    id: bigint;
    status: SettlementStatus;
    endDate: Timestamp;
    statementIds: Array<bigint>;
    closingBalances: Array<[bigint, RepBalance]>;
    openingBalances: Array<[bigint, RepBalance]>;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_SettlementStatus_n4(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        statementIds: value.statementIds,
        closingBalances: value.closingBalances,
        openingBalances: value.openingBalances,
        startDate: value.startDate
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): SettlementStatus {
    return "closed" in value ? SettlementStatus.closed : "open" in value ? SettlementStatus.open : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SettlementPeriodView>): Array<SettlementPeriodView> {
    return value.map((x)=>from_candid_SettlementPeriodView_n2(_uploadFile, _downloadFile, x));
}
function to_candid_SettlementStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SettlementStatus): _SettlementStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SettlementStatus): {
    closed: null;
} | {
    open: null;
} {
    return value == SettlementStatus.closed ? {
        closed: null
    } : value == SettlementStatus.open ? {
        open: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
